In [1]:
#import packages
from arcgis import GIS
import pandas as pd
from arcgis.features import GeoAccessor

/opt/conda/lib/python3.7/site-packages/arcgis/features/_data/geodataset/utils.py:16: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  pd.datetime,

In [2]:
#Authenticate our GIS object
gis = GIS(url='https://NSOE.maps.arcgis.com',username='xf35_790')

Enter password: ········

In [3]:
#Read local datasets into spatial dataframes
sdf_Exits = GeoAccessor.from_featureclass('../Data/MJBA/MJBA_Exits.shp')
sdf_floods = GeoAccessor.from_featureclass('../Data/Processed/exits_flood.shp')
sdf_EucDist = GeoAccessor.from_featureclass('../Data/Processed/Exits_distance_to_DCFC.shp')
sdf_AmenityCount = GeoAccessor.from_featureclass('../Data/Processed/exits_amenities.shp')
sdf_DriveDist = GeoAccessor.from_featureclass('../Data/Processed/exits_distance.shp')
sdf_DisToPower = GeoAccessor.from_featureclass('../Data/Processed/Exits_distance_to_Power.shp')

In [4]:
#Subset fields from the Exits feature class and set FID to the index
sdf_Exits = sdf_Exits[['FID','Longitude', 'Latitude', 'County', 'State','SHAPE']].set_index('FID')

In [5]:
sdf_floods.head()

,level_0,index,FID,Exit_ID,Longitude,Latitude,County,State,Highway,Type,AADT,Pop_dens,Comm_1mi,Ports_5mi,Ports_10mi,Ports_20mi,Close_nonT,Flood_Zone,SHAPE
0,0,0,7059,US-64_Cherokee_NC_Exit_1,-84.314304,35.019492,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3700,60.34979,1,0,0,0,34.094152,Area of Minimal Flood Hazard,"{'x': -84.31430368976345, 'y': 35.019491849669..."
1,1,1,7060,US-64_Cherokee_NC_Exit_2,-84.311492,35.014933,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3700,60.34979,1,0,0,0,34.365230,Area of Minimal Flood Hazard,"{'x': -84.31149165991212, 'y': 35.014933379571..."
2,2,2,7061,US-64_Cherokee_NC_Exit_3,-84.295528,35.013561,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,35.233979,Area of Minimal Flood Hazard,"{'x': -84.29552778977563, 'y': 35.013560589649..."
3,3,3,7062,US-64_Cherokee_NC_Exit_4,-84.280291,35.012880,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,36.048303,Area of Minimal Flood Hazard,"{'x': -84.28029090010494, 'y': 35.012879950349..."
4,4,4,7063,US-64_Cherokee_NC_Exit_5,-84.275190,35.017816,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,36.186597,Area of Minimal Flood Hazard,"{'x': -84.27519011992803, 'y': 35.017816120417..."

In [6]:
sdf_AmenityCount.head()

,index,FID,Exit_ID,Longitude,Latitude,County,State,Highway,Type,AADT,Pop_dens,Comm_1mi,Ports_5mi,Ports_10mi,Ports_20mi,Close_nonT,amenity_n,SHAPE
0,0,7059,US-64_Cherokee_NC_Exit_1,-84.314304,35.019492,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3700,60.34979,1,0,0,0,34.094152,0,"{'x': -84.31430368976345, 'y': 35.019491849669..."
1,1,7060,US-64_Cherokee_NC_Exit_2,-84.311492,35.014933,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3700,60.34979,1,0,0,0,34.365230,0,"{'x': -84.31149165991212, 'y': 35.014933379571..."
2,2,7061,US-64_Cherokee_NC_Exit_3,-84.295528,35.013561,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,35.233979,0,"{'x': -84.29552778977563, 'y': 35.013560589649..."
3,3,7062,US-64_Cherokee_NC_Exit_4,-84.280291,35.012880,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,36.048303,0,"{'x': -84.28029090010494, 'y': 35.012879950349..."
4,4,7063,US-64_Cherokee_NC_Exit_5,-84.275190,35.017816,Cherokee,NC,U.S. Highway 64,Exit/Intersection,3900,60.34979,0,0,0,0,36.186597,0,"{'x': -84.27519011992803, 'y': 35.017816120417..."

In [7]:
sdf_DisToPower.columns

Index(['index', 'FID', 'Exit_ID', 'Longitude', 'Latitude', 'County', 'State',
       'Highway', 'Type', 'AADT', 'Pop_dens', 'Comm_1mi', 'Ports_5mi',
       'Ports_10mi', 'Ports_20mi', 'Close_nonT', 'Dist_to_Pw', 'SHAPE'],
      dtype='object')

In [8]:
#Remove extraneous columns
sdf_floods = sdf_floods[['FID','Flood_Zone']].set_index('FID')
sdf_EucDist = sdf_EucDist[['FID','Dist_to_DC']].set_index('FID')
sdf_AmenityCount = sdf_AmenityCount[['FID','amenity_n']].set_index('FID')
sdf_DriveDist = sdf_DriveDist[['FID','distance']].set_index('FID')
sdf_DisToPower = sdf_DisToPower[['FID','Dist_to_Pw']].set_index('FID')

In [24]:
sdf_AmenityCount.head()

      amenity_n
FID
7059          0
7060          0
7061          0
7062          0
7063          0

In [9]:
sdf_Exits.head()

,Longitude,Latitude,County,State,SHAPE
FID,,,,,
7059,-84.314304,35.019492,Cherokee,NC,"{'x': -84.31430368976345, 'y': 35.019491849669..."
7060,-84.311492,35.014933,Cherokee,NC,"{'x': -84.31149165991212, 'y': 35.014933379571..."
7061,-84.295528,35.013561,Cherokee,NC,"{'x': -84.29552778977563, 'y': 35.013560589649..."
7062,-84.280291,35.012880,Cherokee,NC,"{'x': -84.28029090010494, 'y': 35.012879950349..."
7063,-84.275190,35.017816,Cherokee,NC,"{'x': -84.27519011992803, 'y': 35.017816120417..."

In [10]:
sdf_floods.head()

                        Flood_Zone
FID
7059  Area of Minimal Flood Hazard
7060  Area of Minimal Flood Hazard
7061  Area of Minimal Flood Hazard
7062  Area of Minimal Flood Hazard
7063  Area of Minimal Flood Hazard

In [11]:
#Merge all datasets into a single exit dataset
sdf_Master = pd.merge(left=sdf_Exits,right=sdf_floods,how='left',left_index=True,right_index=True)
sdf_Master = pd.merge(left=sdf_Master,right=sdf_EucDist,how='left',left_index=True,right_index=True)
sdf_Master = pd.merge(left=sdf_Master,right=sdf_AmenityCount,how='left',left_index=True,right_index=True)
sdf_Master = pd.merge(left=sdf_Master,right=sdf_DriveDist,how='left',left_index=True,right_index=True)
sdf_Master = pd.merge(left=sdf_Master,right=sdf_DisToPower,how='left',left_index=True,right_index=True)

In [12]:
sdf_Master.head()

,Longitude,Latitude,County,State,SHAPE,Flood_Zone,Dist_to_DC,amenity_n,distance,Dist_to_Pw
FID,,,,,,,,,,
7059,-84.314304,35.019492,Cherokee,NC,"{'x': -84.31430368976345, 'y': 35.019491849669...",Area of Minimal Flood Hazard,103,0,NaN,5.987276
7060,-84.311492,35.014933,Cherokee,NC,"{'x': -84.31149165991212, 'y': 35.014933379571...",Area of Minimal Flood Hazard,102,0,NaN,5.879956
7061,-84.295528,35.013561,Cherokee,NC,"{'x': -84.29552778977563, 'y': 35.013560589649...",Area of Minimal Flood Hazard,102,0,NaN,5.014686
7062,-84.280291,35.012880,Cherokee,NC,"{'x': -84.28029090010494, 'y': 35.012879950349...",Area of Minimal Flood Hazard,101,0,NaN,4.193707
7063,-84.275190,35.017816,Cherokee,NC,"{'x': -84.27519011992803, 'y': 35.017816120417...",Area of Minimal Flood Hazard,100,0,NaN,3.823759

In [13]:
#Rename columns
sdf_Master.rename(columns={'Dist_to_DC':'Mi_to_DCFC',
                           'amenities':'No_amenities',
                           'distance':'RdMi_to_DCFC'},inplace=True)

In [14]:
sdf_Master.head()

,Longitude,Latitude,County,State,SHAPE,Flood_Zone,Mi_to_DCFC,amenity_n,RdMi_to_DCFC,Dist_to_Pw
FID,,,,,,,,,,
7059,-84.314304,35.019492,Cherokee,NC,"{'x': -84.31430368976345, 'y': 35.019491849669...",Area of Minimal Flood Hazard,103,0,NaN,5.987276
7060,-84.311492,35.014933,Cherokee,NC,"{'x': -84.31149165991212, 'y': 35.014933379571...",Area of Minimal Flood Hazard,102,0,NaN,5.879956
7061,-84.295528,35.013561,Cherokee,NC,"{'x': -84.29552778977563, 'y': 35.013560589649...",Area of Minimal Flood Hazard,102,0,NaN,5.014686
7062,-84.280291,35.012880,Cherokee,NC,"{'x': -84.28029090010494, 'y': 35.012879950349...",Area of Minimal Flood Hazard,101,0,NaN,4.193707
7063,-84.275190,35.017816,Cherokee,NC,"{'x': -84.27519011992803, 'y': 35.017816120417...",Area of Minimal Flood Hazard,100,0,NaN,3.823759

In [15]:
#Optional: Save to a new local shapefile
sdf_Master.spatial.to_featureclass('../Data/Processed/Final_Exits.shp')

'../Data/Processed/Final_Exits.shp'

In [16]:
#Import NREL csv as datafram
DCFC_df = pd.read_csv('../Data/NREL/DCFC.csv')

In [17]:
# Convert datafram to arcgis spatial dataframe
DCFC_sdf = GeoAccessor.from_xy(DCFC_df,x_column = 'longitude',y_column = 'latitude', sr = 4326)

In [18]:
#Convert the DCFC_sdf to a FeatureLayer, which publishes it to AGOL
DCFC_flyr = DCFC_sdf.spatial.to_featurelayer(title='NREL DC Fast Charger sites',
                                             tags='EV Charger,ENV790')
DCFC_flyr

In [19]:
#Construct the dictionary of feature layer properties
featLayer_properties = {
    'snippet':"NREL DC Fast Charging site. Extracted and subset via the NREL API",
    'summary':"These data were extracted from the NREL API, subset using the following criteria..."
}
#Apply the changes
DCFC_flyr.update(featLayer_properties)

True

In [20]:
DCFC_flyr

In [21]:
#Share with everyone in the organization
DCFC_flyr.share(org=True)

{'results': [{'itemId': 'c9a388ee502940b38fccd375155bc5a9',
   'success': True,
   'notSharedWith': []}]}

In [22]:
#Convert the sdf_Master to a FeatureLayer, which publishes it to AGOL
flyr_master = sdf_Master.spatial.to_featurelayer(title='Candidate Charger sites',
                                             tags='EV Charger,ENV790')

In [23]:
#Share with everyone in the organization
flyr_master.share(org=True)

{'results': [{'itemId': 'd6126a5f5636434e942a44df136f396d',
   'success': True,
   'notSharedWith': []}]}